import type { PrototypeHeroSummary, PrototypeTabHero, QuickItem } from './types';

export const quickItems: QuickItem[] = [
  {
    icon: 'ticket',
    title: '购票',
    desc: '购买体验票，现场核销入场',
    bg: 'from-[#A8171E] to-[#D64B26]',
  },
  {
    icon: 'play',
    title: '开始体验',
    desc: '进入剧情任务，开启英雄挑战',
    bg: 'from-[#B51C23] to-[#7D1218]',
  },
  {
    icon: 'users',
    title: '加入队伍',
    desc: '输入队伍码，和朋友一起玩',
    bg: 'from-[#7E171D] to-[#C73820]',
  },
  {
    icon: 'watch',
    title: '绑定手环',
    desc: '查看心率、血氧、心流状态',
    bg: 'from-[#9B1D1D] to-[#D99938]',
  },
];

export const homeHeroes: PrototypeHeroSummary[] = [
  {
    name: '霍去病',
    tag: '少年将军',
    time: '90分钟',
    diff: '中等难度',
    tone: 'from-[#621013] via-[#A4151C] to-[#E1A83A]',
  },
  {
    name: '花木兰',
    tag: '巾帼英雄',
    time: '75分钟',
    diff: '简单难度',
    tone: 'from-[#711619] via-[#B0262A] to-[#E7B956]',
  },
  {
    name: '岳飞',
    tag: '精忠报国',
    time: '100分钟',
    diff: '中等难度',
    tone: 'from-[#5C1115] via-[#9B1A1F] to-[#C78C2E]',
  },
];

export const allHeroes: PrototypeTabHero[] = [
  {
    id: 'h1',
    name: '霍去病',
    subtitle: '少年将军 · 封狼居胥',
    tag: '少年英雄',
    line: '封狼居胥挑战线',
    duration: '90分钟',
    tasks: 6,
    difficulty: '中等',
    status: '可体验',
    unlocked: true,
    image: 'https://images.unsplash.com/photo-1621619856624-42fd193a0661?q=80&w=2658&auto=format&fit=crop',
  },
  {
    id: 'h2',
    name: '花木兰',
    subtitle: '代父从军 · 巾帼英雄',
    tag: '巾帼英雄',
    line: '忠义千秋体验路',
    duration: '75分钟',
    tasks: 5,
    difficulty: '简单',
    status: '可体验',
    unlocked: true,
    image: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'h3',
    name: '岳飞',
    subtitle: '精忠报国 · 民族脊梁',
    tag: '家国英雄',
    line: '满江红怒发冲冠线',
    duration: '100分钟',
    tasks: 6,
    difficulty: '中等',
    status: '可体验',
    unlocked: true,
    image: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?q=80&w=2732&auto=format&fit=crop',
  },
  {
    id: 'h4',
    name: '诸葛亮',
    subtitle: '卧龙出山 · 智谋千古',
    tag: '智谋英雄',
    line: '赤壁借箭烧营策',
    duration: '80分钟',
    tasks: 5,
    difficulty: '困难',
    status: '即将开放',
    unlocked: false,
    image: 'https://images.unsplash.com/photo-1621619856624-42fd193a0661?q=80&w=2658&auto=format&fit=crop',
  },
  {
    id: 'h5',
    name: '秦始皇',
    subtitle: '一统六国 · 千古一帝',
    tag: '智谋英雄',
    line: '万里长城筑魂记',
    duration: '120分钟',
    tasks: 8,
    difficulty: '困难',
    status: '未解锁',
    unlocked: false,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=2680&auto=format&fit=crop',
  },
];
